version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'ci(github)'
    labels: ['tech. enhancement']

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'build(deps)'
      prefix-development: 'build(dev-deps)'
    labels: ['tech. enhancement']
    groups:
      non-major-dependencies:
        applies-to: version-updates
        dependency-type: production
        update-types: ['minor', 'patch']
      non-major-dev-dependencies:
        applies-to: version-updates
        dependency-type: development
        update-types: ['minor', 'patch']

  - package-ecosystem: 'npm'
    directory: '/cypress'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'build(dev-deps)'
      prefix-development: 'build(dev-deps)'
    labels: ['tech. enhancement']
    groups:
      non-major-dependencies:
        applies-to: version-updates
        dependency-type: production
        update-types: ['minor', 'patch']
      non-major-dev-dependencies:
        applies-to: version-updates
        dependency-type: development
        update-types: ['minor', 'patch']
