name: E2E

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test_e2e:
    name: E2E Test
    runs-on: ubuntu-latest
    container: cypress/browsers:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: |
          npm ci
          npm --prefix cypress ci
      - name: Test
        run: |
          chmod o+w /__w/cypress-plugin-snapshots/cypress-plugin-snapshots/cypress
          ls -la /__w/cypress-plugin-snapshots/cypress-plugin-snapshots/cypress
          npm run ci:test
          kill $(jobs -p) || true
      - name: Archive Cypress snapshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-snapshots
          path: cypress/cypress/e2e/__image_snapshots__
