name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 20
      - name: Install
        run: yarn --immutable
      - name: Test
        run: |
          chmod o+w /__w/cypress-plugin-snapshots/cypress-plugin-snapshots/cypress
          ls -la /__w/cypress-plugin-snapshots/cypress-plugin-snapshots/cypress
          npm run ci:test
          kill $(jobs -p) || true
      - name: Archive Cypress snapshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-snapshots
          path: cypress/cypress/integration/__*snapshots__/*
